// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbbugtrsoxapaolrkfxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiYnVndHJzb3hhcGFvbHJrZnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyODA3MjcsImV4cCI6MjA2MTg1NjcyN30.jMGzlZgM0FfZjlzjbz4ChQDAi--WNPhE-09xGW4fMmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);